service: market-backend

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

functions:
  createMarket:
    handler: index.handler
    events:
      - http:
          method: POST
          path: /market
  getMarkets:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /markets
  getMarket:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /market/{id}
  updateMarket:
    handler: index.handler
    events:
      - http:
          method: PUT
          path: /market/{id}
  deleteMarket:
    handler: index.handler
    events:
      - http:
          method: DELETE
          path: /market/{id}
  getCountries:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /countries
  getCurrencies:
    handler: index.handler
    events:
      - http:
          method: GET
          path: /currencies

plugins:
  - serverless-offline
